#!/bin/sh
# generates a cobol copybook with every logo/*.txt baked in,
# so the binary does not need the logo folder at runtime.
# usage: ./gen-logos.sh logo/*.txt > build/logos.cpy

LC_ALL=C awk '
function flush() {
    if (id == "") return
    if (count < 32)
        printf "    05 FILLER PIC X(%d) VALUE SPACES.\n", (32 - count) * 32
}

FNR == 1 {
    flush()
    id = FILENAME
    sub(/.*\//, "", id)
    sub(/\.txt$/, "", id)
    count = 0
    total++
    printf "    05 FILLER PIC X(32) VALUE \"%s\".\n", id
    printf "    05 FILLER PIC 99 VALUE %d.\n", (lines[FILENAME] > 32 ? 32 : lines[FILENAME])
}

count < 32 {
    line = substr($0, 1, 32)
    sub(/\r$/, "", line)
    gsub(/"/, "\"\"", line)
    if (line == "")
        printf "    05 FILLER PIC X(32) VALUE SPACES.\n"
    else
        printf "    05 FILLER PIC X(32) VALUE \"%s\".\n", line
    count++
}

BEGIN {
    # count lines first so each entry can store its own line count
    for (i = 1; i < ARGC; i++) {
        n = 0
        while ((getline l < ARGV[i]) > 0) n++
        close(ARGV[i])
        lines[ARGV[i]] = n
    }
    print "*> generated by gen-logos.sh from logo/*.txt, do not edit"
    print "01 LOGO-DATA."
}

END {
    flush()
    print "01 LOGO-DB REDEFINES LOGO-DATA."
    printf "    05 LOGO-ENTRY OCCURS %d TIMES.\n", total
    print "        10 LOGO-ENTRY-ID    PIC X(32)."
    print "        10 LOGO-ENTRY-COUNT PIC 99."
    print "        10 LOGO-ENTRY-LINE  PIC X(32) OCCURS 32 TIMES."
    printf "01 LOGO-ENTRY-TOTAL PIC 99 VALUE %d.\n", total
}
' "$@"
